exceptions = %w(
  PermissionDenied
  InvalidState
  DuplicatedPhone
  DuplicatedName
  InvalidCard
  InvalidMember
  CannotBeBlank
  DoesNotExist
  AlreadyInUse
  InvalidParameter
  UserNotFound
  UnactivatedUser
  IncorrectVerificationCode
  DuplicatedMembership
  DuplicatedVacancy
  UndeterminedItem
  InvalidCardType
  InvalidCharingType
  InsufficientBall
  InsufficientMinute
  InsufficientDeposit
  InvalidItem
  InvalidChargingType
  MemberExists
  NoUseRights
  DuplicatedReservation
  NoPrice
  NonUniqueMember
  InvalidBucket
  InvalidConfirmMethod
  InvalidUser
  OriginPriceNotFound
  InvalidDiscount
  FrequentRequest
  TooManyRequest
  FullLesson
  AlreadyReserved
)
exceptions.each{|e| Object.const_set(e, Class.new(StandardError))} 